{% set name = "swmmtoolbox" %}
{% set version = "4.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/swmmtoolbox-{{ version }}.tar.gz
  sha256: 2bcf39659566044481a4911b09a939d28e90bf9bd2c8a63699dfa34552da8dc1

build:
  entry_points:
    - swmmtoolbox = swmmtoolbox.swmmtoolbox:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.8
    - toolbox_utils >=5.0.0,<6.0.0
    - cltoolbox >=1.0.0

test:
  imports:
    - swmmtoolbox
  commands:
    - pip check
    - swmmtoolbox --help
  requires:
    - pip

about:
  summary: Command line script and Python library to read Storm Water Management Model binary output.
  home: https://pypi.org/project/swmmtoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
